// const p1:PlayerState = {
//     id: 0,
//     name: "Player 1",
//     role: 0,
//     location: 2,
//     cards: []
// };

// const p2:PlayerState = {
//     id: 1,
//     name: "Player 2",
//     role: 1,
//     location: 3,
//     cards: []
// };

// const b1:BoardState = {
//     players: [ p1, p2 ],
//     currentPlayer: 0,
//     actionsRemaining: 3,
//     tiles: [],
//     waterLevel: 0,
//     treasureStack: [],
//     treasureDiscard:number[];
//     treasureCardsToDraw:number;
//     floodStack:number[];
//     floodDiscard:number[];
//     floodCardsToDraw:number;
//     startupComplete:boolean;
// }

export const b_start = {
    players: [
      { id: 0, name: "Player 1", role: 5, location: 19, cards: [19, 6] },
      { id: 1, name: "Player 2", role: 2, location: 18, cards: [23, 14] }
    ],
    tiles: [
      null,
      null,
      { id: 12, flooded: false },
      { id: 15, flooded: false },
      null,
      null,
      null,
      { id: 21, flooded: false },
      { id: 10, flooded: false },
      { id: 22, flooded: false },
      { id: 5, flooded: false },
      null,
      { id: 17, flooded: false },
      { id: 16, flooded: false },
      { id: 0, flooded: false },
      { id: 23, flooded: false },
      { id: 11, flooded: false },
      { id: 3, flooded: false },
      { id: 4, flooded: false },
      { id: 20, flooded: false },
      { id: 2, flooded: false },
      { id: 6, flooded: false },
      { id: 1, flooded: false },
      { id: 18, flooded: false },
      null,
      { id: 7, flooded: false },
      { id: 8, flooded: false },
      { id: 19, flooded: false },
      { id: 14, flooded: false },
      null,
      null,
      null,
      { id: 13, flooded: false },
      { id: 9, flooded: false },
      null,
      null
    ],
    currentPlayer: null,
    actionsRemaining: null,
    waterLevel: 0,
    treasureStack: [
      1,
      12,
      26,
      4,
      10,
      3,
      25,
      8,
      24,
      20,
      21,
      22,
      18,
      7,
      11,
      13,
      0,
      15,
      16,
      2,
      5,
      9,
      27,
      17
    ],
    treasureDiscard: [],
    treasureCardsToDraw: 0,
    floodStack: [
      7,
      15,
      3,
      18,
      12,
      16,
      8,
      22,
      6,
      13,
      21,
      5,
      2,
      19,
      14,
      17,
      11,
      4,
      10,
      1,
      23,
      20,
      9,
      0
    ],
    floodDiscard: [],
    floodCardsToDraw: 6,
    startupComplete: false
  };
  
  export const b1 = {
      players: [
        { id: 0, name: "Player 1", role: 5, location: 19, cards: [19, 6] },
        { id: 1, name: "Player 2", role: 2, location: 18, cards: [23, 14] },
        { id: 2, name: "Player 3", role: 1, location: 18, cards: [] }
      ],
      tiles: [
        null,
        null,
        { id: 10, flooded: false },
        { id: 11, flooded: true },
        null,
        null,
        null,
        { id: 21, flooded: false },
        { id: 12, flooded: false },
        { id: 22, flooded: false },
        { id: 5, flooded: false }, // 10 - Cafe 1923 (2 coffee)
        null,
        { id: 17, flooded: false },
        { id: 16, flooded: false },
        { id: 0, flooded: false },
        { id: 23, flooded: false },
        { id: 15, flooded: false },
        { id: 3, flooded: false },
        { id: 4, flooded: false },  // 18 - Aladdin Sweets & Cafe (1 meal)
        { id: 20, flooded: false }, // 19
        { id: 2, flooded: false },
        { id: 6, flooded: false },
        { id: 1, flooded: false },
        { id: 18, flooded: false },
        null,
        { id: 7, flooded: false },
        { id: 8, flooded: false },
        { id: 19, flooded: false },
        { id: 14, flooded: false },
        null,
        null,
        null,
        { id: 13, flooded: false },
        { id: 9, flooded: false },
        null,
        null
      ],
      currentPlayer: 0,
      actionsRemaining: 3,
      waterLevel: 0,
      treasureStack: [
        1,
        12,
        26,
        4,
        10,
        3,
        25,
        8,
        24,
        20,
        21,
        22,
        18,
        7,
        11,
        13,
        0,
        15,
        16,
        2,
        5,
        9,
        27,
        17
      ],
      treasureDiscard: [],
      treasureCardsToDraw: 0,
      floodStack: [ 
        7,
        15,
        3,
        18,
        12,
        16,
        8,
        22,
        6,
        13,
        21,
        5,
        2,
        19,
        14,
        17,
        11,
        4,
        10,
        1,
        23,
        20,
        9,
        0
      ],
      floodDiscard: [],
      floodCardsToDraw: 0,
      startupComplete: false
    };
  
  // console.log(JSON.stringify(getInitialBoard(2, 0)));